### ISSUE TITLE
Fail to Connect to Database - Could you include SQLite files instead?

### ISSUE THREAD

**Issue by dtdannen** [xflows/rdm#3]
Hi,

This looks like a great project and I'd like to consider using it my research, however neither example (imdb.py or trains.py) works because it is not possible to connect to the mysql server you specify:

```
# Provide connection information
connection = DBConnection(
    'ilp',  # User
    'ilp123',  # Password
    'workflow.ijs.si',  # Host
    'imdb_top',  # Database
    vendor=DBVendor.MySQL
)
```

Would you consider exporting the database data into a sqlite file and then uploading to the github repository? Or check that the connection to the MySQL server is open? I tried connecting from the United States.

Thank you for considering this!

**Comment by SkBlaz** [comment]
Hello, albeit late, python3-new branch now operates on local files (more or less). You simply download the file by using one of the converters (https://github.com/xflows/rdm/blob/python3-new/benchmark_studies/get_datasets.py). This generates a pickle file, which can easily  be loaded from wherever one wants.

Hope this helps.

**Comment by vpodpecan** [comment]
It is now possible to read SQLite databases and CSV files. Check the documentation [here](https://python-rdm.readthedocs.io/en/latest/). Just make sure that you install the latest version from PyPi.
