### ISSUE TITLE
Problems installing in Mac OS 15 M1

### ISSUE THREAD

**Issue by joofio** [xflows/rdm#6]
Tried several installation methods, tried installing psycopg2 and libpq and still not working.

The current error is in line "from rdm.db import CSVConnection"
The error is:
"ModuleNotFoundError: No module named 'rdm.db'"

Does someone have tips to make this work?

**Comment by vpodpecan** [comment]
Please try first this notebook and report if you encounter the same issue:
[https://github.com/vpodpecan/representation_learning/blob/master/Chapter4/python-rdm.ipynb](https://github.com/vpodpecan/representation_learning/blob/master/Chapter4/python-rdm.ipynb)

**Comment by joofio** [comment]
Thanks for the response! will return with feedback ASAP

**Comment by joofio** [comment]
Worked perfectly so far! Thanks for the help
